### ISSUE TITLE
[Addition] Radon for 1.18.X

### ISSUE THREAD

**Issue by PhoenixEvolver** [NordicGamerFE/usefulmods#105]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Radon

### What is your mod's main version?

1.18.X (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/radon

### What is your reasoning for including this mod?

It is not included in the 1.18.X list of performance mods.

### (OPTIONAL) Give some extra information about the mod.

Radon is an Unofficial Fork of CaffeineMC's "Phosphor", made to work with Forge Mod Loader.

**Comment by lrmtheboss** [comment]
Is already a PR #79
