### ISSUE TITLE
[Correction] Clumps seems to be server side nowadays

### ISSUE THREAD

**Issue by FnigePython** [NordicGamerFE/usefulmods#107]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Clumps

### What is your mod's main version?

1.17.X (Fabric)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/clumps

### What is your reasoning for including this mod?

Versions past 1.17 are now only needed on the server instead of the client.

### (OPTIONAL) Give some extra information about the mod.

Oh and also. You should have a correction form for situations like this. So people arent forced to use another form not made for corrections.

**Comment by lrmtheboss** [comment]
I made a correction issue template in pr #109, you can look at it and suggest changes on that pr

As for your correction do you have and documentation to support that its only server side now?

**Comment by FnigePython** [comment]
Mostly just going off of what it says on curseforge
![image](https://user-images.githubusercontent.com/35159947/180700859-c66de84f-0451-4ef4-8675-c87f21c57ec5.png)
