### ISSUE TITLE
[Addition] FastWorkbench

### ISSUE THREAD

**Issue by WFPhantom** [NordicGamerFE/usefulmods#11]
Mod name: FastWorkbench

Mod version: forge 1.16 4.6.1

Mod Links: https://www.curseforge.com/minecraft/mc-mods/fastworkbench

The reasoning for Inclusion: While fastworkbench minus replacement is already on the list, this one should theoretically be faster because it removes the recipe book. Afaik the minus replacement version was made only for mod compatability so if you are playing on something lightly modded and need more fps the normal one should theoretically be better. There should be no case In which fastfurnace is better than fast furnace minus replacement though so just fastworkbench.

Other Information:

**Comment by GeefireMC** [comment]
Is there any actual measurable performance difference compared to the currently listed mod? Being _theoretically_ better isn't really worth it if it's not _practically_ better. I can't seem to find anything comparing the two online.

**Comment by WFPhantom** [comment]
Ah actually the performance boost is only in 1.12, in 1.13 the recipe book is synced to the new recipe system. Minus replacement is not available in 1.16 anyways so that's my bad.
