### ISSUE TITLE
[Correction] dashLoader is compatible with Enhanced block entities

### ISSUE THREAD

**Issue by evhunter09** [NordicGamerFE/usefulmods#120]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

EBE and dashLoader, and cull leaves and moreCulling

### What section(s) of the list is this correction for?

Preformance

### What version(s) dose this correction apply to?

1.18.X (Fabric)

### What needs correcting?

Enhanced block entities is compatible with dashLoader on 1.18.2 and 1.19 so they should be removed from the known incompatibilities, and moreCulling has leaf culling build in.

### Input a link(s) which can be used to verify the correction.

https://user-images.githubusercontent.com/89302916/186462663-116d6b46-9b1c-49c9-aaa9-24eae72733f1.png

### (OPTIONAL) Any extra information about the correction.

Also forgetMeChunk causes a memory leak by not unloading data so you might want to say that but memory leak fix helps with that

**Comment by alexhowell610** [comment]
The author of MemoryLeakFix says that it doesn't do anything for the ForgetMeChunk memory leak and it only fixes Vanilla memory leaks.

![ML_SC](https://user-images.githubusercontent.com/71944107/188702195-b546a6cb-c848-44d2-b4df-22c31741f38d.png)

**Comment by brucethemoose** [comment]
Note that Debugify claims to have already implemented ForgetMeChunk without the memory leak... maybe.

**Comment by evhunter09** [comment]
memoryLeakFix doesn't stop ForgetMeChunk leaking (because the way it works intentionally makes a memory leak) but it helps with other memory leaks, and along with ferrite core, helps with memory usage a lot - which helps ForgetMeChunk
