### ISSUE TITLE
[Correction] Remove Debugify recommendation for Forge 1.18.X and 1.19.X

### ISSUE THREAD

**Issue by falxie** [NordicGamerFE/usefulmods#125]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Debugify

### What section(s) of the list is this correction for?

Bugfixes

### What version(s) dose this correction apply to?

1.18.X (Forge), Other (Forge)

### What needs correcting?

I don't think that Debugify should be recommended for 1.18 or 1.19 Forge seeing that the developer has decided to not support it. The mod also only seems to only be actively supported for the latest version of Minecraft which has caused issues for me with JEI 1.18.

### Input a link(s) which can be used to verify the correction.

Forge support removed: https://github.com/isXander/Debugify/pull/136
JEI bug (fixed in 1.19 but not backported to 1.18): https://github.com/isXander/Debugify/issues/74

**Comment by 06000208** [comment]
Additional context regarding debugify stealing code from other people's mods:
https://gist.github.com/fxmorin/9770473614e3e5e0703e44273dab33f7
