### ISSUE TITLE
[Addition] Magnesium

### ISSUE THREAD

**Issue by IntoTheVoid-900** [NordicGamerFE/usefulmods#36]
### Checklist

- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.
- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.

### What is your mod's name?

Magnesium

### What is your mod's main version?

1.18.X (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/sodium-reforged

### What is your reasoning for including this mod?

It was already listed for 1.16, but Magnesium is also updated to 1.18 and in the same state as Sodium's latest alpha. Please list it with forge 1.18 performance mods.

### (OPTIONAL) Give some extra information about the mod.

Forge port of Sodium/

**Comment by yesn0t** [comment]
added, thanks !
