### ISSUE TITLE
Rubidium[Addition]

### ISSUE THREAD

**Issue by freopt** [NordicGamerFE/usefulmods#39]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Rubidium

### What is your mod's main version?

1.18.X (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/rubidium

### What is your reasoning for including this mod?

Forge port of sodium thats actually being maintained, unlike magnesium
also magnesium doesnt work on 1.18.1

**Comment by GeefireMC** [comment]
Magnesium has 1.18 builds listed.
