### ISSUE TITLE
Starlight x Create not for 1.18?

### ISSUE THREAD

**Issue by 06000208** [NordicGamerFE/usefulmods#48]
Added in https://github.com/NordicGamerFE/usefulmods/commit/9ab6f4cd729e30f30af058d03c139293b22a0f20, the fact its in performance118.md, the description given, and the summary if you view it from the [author's projects list](https://www.curseforge.com/members/siromgitsyou/projects) all suggest that it supports 1.18:
![image](https://user-images.githubusercontent.com/52764066/156266777-88ef2b02-14e2-4244-acff-f6815e3bc77e.png)

However, if you [follow the link](https://www.curseforge.com/minecraft/mc-mods/starlight-x-create) 1.18 isn't mentioned anywhere in the description or page, and both files ([v1.1](https://www.curseforge.com/minecraft/mc-mods/starlight-x-create/files/3581601), [v1.2](https://www.curseforge.com/minecraft/mc-mods/starlight-x-create/files/3583654)) are marked as only supporting 1.16.

Are the versions mislabeled and it does support 1.18, or is it mislabeled as supporting 1.18 when it doesn't?

**Comment by NordicGamerFE** [comment]
starlight for 1.18 has fixed this issue and starlight + create is no longer needed

**Comment by 06000208** [comment]
Great! So it should be removed from [Performance118.md](https://github.com/NordicGamerFE/usefulmods/blob/main/Performance/Performance118.md), right?

**Comment by NordicGamerFE** [comment]
Yes, first gonna ask Peter the creator of the fork and ask him first if he has other plans for the mod or if he's not going to do anything more

**Comment by Pectacular** [comment]
Since Starlight + Create has been removed, I'm closing this issue.
