### ISSUE TITLE
[Software Addition] SKlauncher

### ISSUE THREAD

**Issue by RDKRACZ** [NordicGamerFE/usefulmods#52]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

SKlauncher

### What systems do you know your software works on?

- [X] Windows 11
- [X] Windows 10
- [ ] Windows 8/8.1
- [ ] Windows 7
- [ ] Windows XP or earlier
- [X] MacOS
- [X] Linux
- [ ] Other

### Input a link to your suggested software.

https://skmedix.pl/sklauncher

**Comment by ChiefArug** [comment]
Also a pirate launcher.
