### ISSUE TITLE
[Software Addition] PolyMC (MultiMC fork)

### ISSUE THREAD

**Issue by RDKRACZ** [NordicGamerFE/usefulmods#53]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

PolyMC

### What systems do you know your software works on?

- [X] Windows 11
- [X] Windows 10
- [ ] Windows 8/8.1
- [ ] Windows 7
- [ ] Windows XP or earlier
- [ ] MacOS
- [X] Linux
- [X] Other

### Input a link to your suggested software.

https://polymc.org/

### What is your reasoning for including this software?

PolyMC is a MultiMC with a few interesting features like a built-in mod downloader. It is available in many linux package formats like flatpak or appimage, contrary to the multimc.

**Comment by tennox** [comment]
Behind the scenes of [why they forked](https://polymc.org/news/moving-on/)
