### ISSUE TITLE
[Software Addition] VLauncher

### ISSUE THREAD

**Issue by RDKRACZ** [NordicGamerFE/usefulmods#54]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

Vortex Launcher

### What systems do you know your software works on?

- [X] Windows 11
- [X] Windows 10
- [ ] Windows 8/8.1
- [ ] Windows 7
- [ ] Windows XP or earlier
- [ ] MacOS
- [X] Linux
- [ ] Other

### Input a link to your suggested software.

https://github.com/Kron4ek/minecraft-vortex-launcher

### What is your reasoning for including this software?

It's a super minimal MC launcher
![image](https://user-images.githubusercontent.com/43277609/158039435-37105d30-7ce1-4250-b949-5043a6892d18.png)

**Comment by ChiefArug** [comment]
This is also a pirate launcher.
