### ISSUE TITLE
[Software Addition] Chunk Launcher

### ISSUE THREAD

**Issue by RDKRACZ** [NordicGamerFE/usefulmods#55]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

Chunk Launcher

### What systems do you know your software works on?

- [X] Windows 11
- [X] Windows 10
- [X] Windows 8/8.1
- [X] Windows 7
- [ ] Windows XP or earlier
- [ ] MacOS
- [X] Linux
- [X] Other

### Input a link to your suggested software.

https://github.com/herbix/chunkLauncher

### What is your reasoning for including this software?

![Screenshot from 2022-03-13 01-19-07](https://user-images.githubusercontent.com/43277609/158039559-ee4e52a5-54d3-4d0e-b361-d948dc8dda93.png)

**Comment by ChiefArug** [comment]
Yet another pirate launcher.
