### ISSUE TITLE
[Addition] to JavaArgumentsOptimization

### ISSUE THREAD

**Issue by EquityX** [NordicGamerFE/usefulmods#59]
This might be a better alternative to Aikars's Flags. In my case this performs better than Aikar's Flags on my system but additional testing is needed to confirm if it is better in all situations.
``` 
-Xms4G -Xmx4G -XX:+UseShenandoahGC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
```
I am no expert in Java & have no idea if all the flags used even apply to Shenandoah. Feel free to correct any mistakes & offer improvements.

**Comment by Pectacular** [comment]
Everything starting with ``` -XX:G1 ``` doesn't apply to Shenandoah and only applies to G1. I'll take a look into all the other flags and see if they're good and if they provide a performance improvement I'll add explanations for them.

**Comment by Pectacular** [comment]
I tried all the other java arguments and they don't provide much of a performance improvement, so I'm not going to add explanations for them
