### ISSUE TITLE
[Software Addition] Catserver/loliserver

### ISSUE THREAD

**Issue by Xplodin** [NordicGamerFE/usefulmods#60]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

LoliServer

### What systems do you know your software works on?

- [X] Windows 11
- [X] Windows 10
- [X] Windows 8/8.1
- [X] Windows 7
- [ ] Windows XP or earlier
- [ ] MacOS
- [X] Linux
- [ ] Other

### Input a link to your suggested software.

https://github.com/Loli-Server/LoliServer

### What is your reasoning for including this software?

The name isnt the best, but I use the software as it works great for 1.16.5 for forge / spigot hybrids
Encountered far less issues with this than mohist, arclight, etc

### (OPTIONAL) Give some extra information about the software.

Is a followup software of catserver on 1.12.2

**Comment by NordicGamerFE** [comment]
I am aware of this, But with the name and all being what is it I am not going to promote it at all
