### ISSUE TITLE
VulcanMod is incompaitable with sodium.

### ISSUE THREAD

**Issue by zbanowanyPL** [NordicGamerFE/usefulmods#76]
Wrote by the mods author on this mod discord.
![Przechwytywanie](https://user-images.githubusercontent.com/90405441/174742314-48a175bb-7f20-4c4b-a833-9bc92f05dd5e.PNG)

**Comment by lrmtheboss** [comment]
what Minecraft version(s) does this apply to? 1.18? 1.17?
Could you provide a link to VulcanMod?

**Comment by zbanowanyPL** [comment]
Link to VulcanMod: https://github.com/xCollateral/VulkanMod/releases
To all because it changes rendering engine to Vulcan so it is not compatible with sodium.
