### ISSUE TITLE
[Addition] 1.19.X - No Chat Reports by Aizistral (Forge and Fabric)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [NordicGamerFE/usefulmods#90]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

1.19.X - No Chat Reports by Aizistral

### What is your mod's main version?

Other (Forge and Fabric) 

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

### What is your reasoning for including this mod?

https://youtu.be/hYAUEMlugyw

This mod helps give server owners back their right to police their own servers.

This is for 1.19.X Forge and Fabric.

This would be considered a bug fix.

### (OPTIONAL) Give some extra information about the mod.

It also helps prevent false bans through spoofed security keys.

**Comment by lrmtheboss** [comment]
Clarification: Mod supports 1.19 only on forge and fabric platforms

**Comment by P3rf3ctXZer0** [comment]
What are you talking about this only supports forge right now. 
![chrome_9KYgmh45GK](https://user-images.githubusercontent.com/10351221/175811692-8dd807de-e73e-405e-821f-f83b971a60d3.png)

**Comment by lrmtheboss** [comment]
if you'll scroll down on that page it has fabric jars as well

**Comment by P3rf3ctXZer0** [comment]
Screenshot. Now please because nothing says fabric anywhere.

**Comment by P3rf3ctXZer0** [comment]
Damn it - its in the file browser. I always forget to look there.
